apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-secret
type: Opaque
stringData:
  password: "rootpassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-secret
type: Opaque
stringData:
  password: "password"
